apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
    env: demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
      env: demo
  template:
    metadata:
      labels:
        app: backend
        env: demo
    spec:
      containers:
        - name: backend-container
          image: niveditsoni/backend-app:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3500
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: MONGO_CONN_STR
              value: mongodb://mongodb-0.mongodb-svc:27017/todo
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-sec
                  key: username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-sec
                  key: password
